jobs:
- job: iOS_CI_on_Mac
  pool:
    vmImage: 'macOS-11'
  variables:
    MACOSX_DEPLOYMENT_TARGET: '10.14'
    CCACHE_DIR: $(Pipeline.Workspace)/ccache
    TODAY: $[format('{0:dd}{0:MM}{0:yyyy}', pipeline.startTime)]
  timeoutInMinutes: 150
  steps:
    - script: |
        brew install ccache
        echo "##vso[task.prependpath]/usr/local/opt/ccache/libexec"
      displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc

    - task: Cache@2
      inputs:
        key: '"$(TODAY)" | "$(Build.SourceBranch)" | "$(Build.SourceVersion)"'
        path: $(CCACHE_DIR)
        restoreKeys: |
          "$(TODAY)" | "$(Build.SourceBranch)"
          "$(TODAY)" |
      displayName: Cach Task

    - script: |
        $(Build.SourcesDirectory)/tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/install_protobuf.sh \
          -p $(Build.BinariesDirectory)/protobuf_install -d $(Build.SourcesDirectory)/cmake/deps.txt
      displayName: Install protobuf


    - script: |
        python3 $(Build.SourcesDirectory)/tools/ci_build/build.py \
          --skip_submodule_sync \
          --build_dir $(Build.BinariesDirectory)/iOS \
          --use_coreml \
          --use_xnnpack \
          --ios \
          --ios_sysroot iphonesimulator  \
          --osx_arch x86_64 \
          --apple_deploy_target 11.0 \
          --use_xcode \
          --config RelWithDebInfo \
          --build_apple_framework \
          --path_to_protoc_exe $(Build.BinariesDirectory)/protobuf_install/bin/protoc \
          --parallel \
          --use_cache \
      displayName: (CPU, CoreML, XNNPACK EPs) Build onnxruntime for iOS x86_64 and run tests using simulator

    - script: |
        ccache -s
        ccache -z
      displayName: Show Cache stats.
