# Add/remove 'ep:ACL' label if issue contains the word 'ACL' or 'acl'
ep:ACL:
  - '(ACL|acl)'
# Add/remove 'ep:ArmNN' label if issue contains the word 'ArmNN' or 'armnn
ep:ArmNN:
  - '(ArmNN|armnn)'
# Add/remove 'ep:CUDA' label if issue contains the word 'CUDA' or 'cuda'
ep:CUDA:
  - '(CUDA|cuda)'
# Add/remove 'ep:DML' label if issue contains the word 'DirectML', 'directml', or 'DML'
ep:DML:
  - '(DirectML|directml|DML)'
# Add/remove 'ep:MIGraphX' label if issue contains the word 'MIGraphX'
ep:MIGraphX:
  - '(MIGraphX)'
# Add/remove 'ep:oneDNN' label if issue contains the word 'oneDNN'
ep:oneDNN:
  - '(oneDNN)'
# Add/remove 'ep:OpenVINO' label if issue contains the word 'OpenVINO', 'openvino', 'OpenVino' or 'Openvino'
ep:OpenVINO:
  - '(OpenVINO|openvino|OpenVino|Openvino)'
# Add/remove 'ep:RockchipNPU' label if issue contains the word 'Rockchip' or 'rockchip'
ep:RockchipNPU:
  - '(Rockchip|rockchip)'
# Add/remove 'ep:TensorRT' label if issue contains the word 'TensorRT', 'tensorrt', 'TRT', or 'Tensorrt'
ep:TensorRT:
  - '(TensorRT|tensorrt|TRT|Tensorrt)'
# Add/remove 'ep:tvm' label if issue contains the word 'TVM' or 'tvm'
ep:tvm:
  - '(TVM|tvm)'
# Add/remove 'ep:VitisAI' label if issue contains the word 'Vitis', 'vitis', or 'VitisAI'
ep:VitisAI:
  - '(Vitis|vitis|VitisAI)'
# Add/remove 'api:JavaScript' label if issue contains the word 'JavaScript', 'javascript', 'nodejs', 'Nodejs', or 'NodeJS'
api:JavaScript:
  - '(JavaScript|javascript|nodejs|Nodejs|NodeJS)'
# Add/remove 'api:Java' label if issue contains the word 'Java' not followed by 'Script'
api:Java:
  - '(Java(?!Script))'
# Add/remove 'api' label if issue contains the word 'C#'
api:CSharp:
  - '(C#)'
# Add/remove 'api' label if issue contains the word 'Python', 'C++', 'C\b', 'Obj-C', or 'WinRT'
api:
  - '(Python|C\+\+|C\b|Obj-C|WinRT)'
# Add/remove 'platform:jetson' label if issue contains the word 'Jetson' or 'jetson'
platform:jetson:
  - '(Jetson|jetson)'
# Add/remove 'platform:windows' label if issue contains the word 'Windows' or 'windows'
platform:windows:
  - '(Windows|windows)'
# Add/remove 'model:transformer' label if issue contains the word 'BERT', 'Bert\b', 'bert\b', 'GPT2', 'gpt2', 'Hugging Face', 'HuggingFace', 'Hugging face', 'Huggingface', 'hugging face', 'huggingface', 'Longformer', 'Long former', 'longformer', 'long former', 'T5', or 't5'
model:transformer:
  - '(BERT|Bert\b|bert\b|GPT2|gpt2|Hugging Face|HuggingFace|Hugging face|Huggingface|hugging face|huggingface|Longformer|Long former|longformer|long former|T5|t5)'
# Add/remove 'quantization' label contains the words 'Is this a quantized model\?\n\nYes', 'Quantization', 'quantization', 'Quantized', or 'quantized' not preceded by 'Is this a '
quantization:
  - '(Is this a quantized model\?\n\nYes|Quantization|quantization|Quantized|(?<!(Is this a ))quantized)'

